"""Build INACCESSIBLE-SOURCES.md (repo root) from data/source-audit/audit-results.jsonl.

Groups every candidate that could NOT be accessed from this environment into:
  A. Blocked by bot protection (WAF)   - even a stealth browser failed
  B. Unreachable from this environment - connection timeout/refused (may work from your network)
  C. Dead / gone                       - 404 / no response / content removed
  D. JS shell / redirect shell         - page loads but is empty (may render in a browser)
  E. Already imported but currently blocked - in the DB already, kept for reference

Run:  python3 scripts/build-inaccessible-list.py
"""
import json, os, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data", "source-audit", "audit-results.jsonl")
OUT = os.path.join(ROOT, "INACCESSIBLE-SOURCES.md")

rows = [json.loads(l) for l in open(SRC)]

ACCESSIBLE = {"OK", "GUIDE"}

def section(title, keys):
    out = [f"## {title}", ""]
    for k in keys:
        r = by_key[k]
        used = " *(already imported)*" if r["kind"] == "used" else ""
        out.append(f"- **{r['name']}**{used} — {r['url']}")
        out.append(f"  - {r['detail']}")
    out.append("")
    return out

# reclassify timeouts as UNREACHABLE (known-alive sites that only timed out),
# and trim long probe details
for r in rows:
    det = r.get("detail", "")
    if r["verdict"] == "DEAD" and ("Timeout" in det or "TIMEOUT" in det):
        r["verdict"] = "UNREACHABLE"
        r["detail"] = "connection timeout"
    if len(det) > 110:
        r["detail"] = det[:107] + "..."

by_key = {r["key"]: r for r in rows}

waf = [r["key"] for r in rows if r["verdict"] == "WAF"]
unreach = [r["key"] for r in rows if r["verdict"] == "UNREACHABLE"]
dead = [r["key"] for r in rows if r["verdict"] == "DEAD"]
shell = [r["key"] for r in rows if r["verdict"] == "JS_SHELL"]
imported_blocked = [r["key"] for r in rows
                    if r["verdict"] in ("WAF", "UNREACHABLE") and r["kind"] == "used"]

# used sources that are blocked belong in section E only
waf = [k for k in waf if by_key[k]["kind"] != "used"]
unreach = [k for k in unreach if by_key[k]["kind"] != "used"]
# keep the used-but-blocked ones listed in E, removing from A/B
imported_blocked_keys = [k for k in imported_blocked]

n_ok = sum(1 for r in rows if r["verdict"] == "OK")
n_guide = sum(1 for r in rows if r["verdict"] == "GUIDE")
n_waf = len(waf)
n_unreach = len(unreach)
n_dead = len(dead)
n_shell = len(shell)

md = []
md.append("# ScholarAtlas — Inaccessible Data Sources (manual extraction list)")
md.append("")
md.append("> Generated by `scripts/audit-sources.py` + `scripts/build-inaccessible-list.py` — "
          "full results in `data/source-audit/audit-results.jsonl` and `audit-summary.txt`.")
md.append("")
md.append("This file lists every candidate data source that **could not be accessed from the "
          "build environment**, so the sources can be extracted manually. Sources in **Section B** "
          "failed only with connection timeouts/refused — they will very likely work from a normal "
          "home/office network. Section A sources need a real (non-headless) browser or manual "
          "copy-paste, because they are behind bot protection.")
md.append("")
md.append("## Sweep summary (2026-08-18)")
md.append("")
md.append("| Verdict | Count | Meaning |")
md.append("|---|---|---|")
md.append(f"| ✅ OK | {n_ok} | Accessible — HTTP 200 with real scholarship content |")
md.append(f"| 📄 Guide | {n_guide} | Accessible — guide pages, no structured listings |")
md.append(f"| 🚧 WAF | {n_waf} | Bot-protection block (Cloudflare/Akamai/WAF) |")
md.append(f"| 🌐 Unreachable | {n_unreach} | Connection timeout/refused from this environment |")
md.append(f"| 💀 Dead | {n_dead} | Gone (404 / no response / removed) |")
md.append(f"| 🧩 JS shell | {n_shell} | Page loads but is an empty JS shell |")
md.append("")
md.append(f"**Tested: {len(rows)} candidates · Accessible to the crawler: {n_ok + n_guide} "
          f"({round(100*(n_ok+n_guide)/len(rows))}%) · Not accessible: "
          f"{n_waf + n_unreach + n_dead + n_shell}**")
md.append("")

# entries already in the catalogue (imported in earlier rounds) get flagged
ALREADY_IMPORTED = {
    "bilkent": "already imported (round-2 direct crawl) — no manual work needed",
    "koc": "already imported (round-2 direct crawl) — no manual work needed",
    "unicamp": "already imported (round-2 direct crawl) — no manual work needed",
}
for k, note in ALREADY_IMPORTED.items():
    if k in by_key and by_key[k]["verdict"] not in ("OK", "GUIDE"):
        by_key[k]["detail"] = by_key[k]["detail"] + "; " + note

md += section(f"A. Blocked by bot protection (WAF) — {len(waf)}", sorted(waf))
md += section(f"B. Unreachable from this environment — {len(unreach)} (likely fine from your network)",
              sorted(unreach))
md += section(f"C. Dead / gone — {len(dead)}", sorted(dead))
md += section(f"D. JS shells / redirect shells — {len(shell)} (may render in a real browser)", sorted(shell))

md.append("## E. Already imported, currently blocked (reference only)")
md.append("")
md.append("These sources are already in the catalogue, so no manual work is needed for them:")
md.append("")
for k in sorted(imported_blocked_keys):
    r = by_key[k]
    md.append(f"- **{r['name']}** — {r['url']}")
    md.append(f"  - {r['detail']}")
md.append("")
md.append("---")
md.append("")
md.append("### How to use this list")
md.append("")
md.append("1. Start with **Section B** (network-temporary) — fetch the listed URLs from your own "
          "machine; most will open normally.")
md.append("2. Then **Section A** — these need a non-headless browser or manual browsing; copy the "
          "scholarship listings into the format used by the existing importers "
          "(`data/uni_direct/records.jsonl` + `scripts/import-uni-direct.ts` for universities, or "
          "a new importer for aggregators).")
md.append("3. **Section D** may render in a browser even though the HTML is empty.")
md.append("4. **Section C** is not worth pursuing unless the domain is resurrected.")

open(OUT, "w").write("\n".join(md))
print(f"Wrote {OUT} ({len(md)} lines)")
